name: Auto Vote

on:
  schedule:
    - cron: '0 */2 * * *'  # This runs the workflow every hour
  push:
    branches:
      - main

jobs:
  vote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run voting script
      run: python main.py
