name: Vote on MCServer-List.eu

on:
  schedule:
    - cron: 0 */2 * * *

jobs:
  vote:
    runs-on: ubuntu-latest
    steps:
      - name: Vote
        env:
          USERNAME: Tlicarek
          VOTE_URL: https://mcserver-list.eu/sk/vote/432
        run: |
          curl -X POST \
            ${VOTE_URL} \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -d "username=${USERNAME}"
