name: Auto Voting Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day

jobs:
  vote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm install

    - name: Run Voting Script
      run: |
        node vote-script.js  # Your voting script in Node.js
      env:
        VOTE_URL: "https://www.minecraft-list.cz/server/dreamland-l-kvalitni-survival-servery/vote?name=Tlicarek"
